# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 611, 111))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 121, 16))
        self.label_2.setObjectName("label_2")
        self.voc_path = QtWidgets.QLineEdit(self.groupBox)
        self.voc_path.setGeometry(QtCore.QRect(170, 30, 331, 21))
        self.voc_path.setObjectName("voc_path")
        self.yolo_path = QtWidgets.QLineEdit(self.groupBox)
        self.yolo_path.setGeometry(QtCore.QRect(170, 70, 331, 21))
        self.yolo_path.setObjectName("yolo_path")
        self.vocSetup = QtWidgets.QPushButton(self.groupBox)
        self.vocSetup.setGeometry(QtCore.QRect(510, 25, 93, 30))
        self.vocSetup.setObjectName("vocSetup")
        self.yoloSetup = QtWidgets.QPushButton(self.groupBox)
        self.yoloSetup.setGeometry(QtCore.QRect(510, 70, 93, 28))
        self.yoloSetup.setObjectName("yoloSetup")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 140, 611, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.label_5.setObjectName("label_5")
        self.train_coef = QtWidgets.QLineEdit(self.groupBox_2)
        self.train_coef.setGeometry(QtCore.QRect(170, 30, 331, 21))
        self.train_coef.setObjectName("train_coef")
        self.val_coef = QtWidgets.QLineEdit(self.groupBox_2)
        self.val_coef.setGeometry(QtCore.QRect(170, 70, 331, 21))
        self.val_coef.setObjectName("val_coef")
        self.test_coef = QtWidgets.QLineEdit(self.groupBox_2)
        self.test_coef.setGeometry(QtCore.QRect(170, 110, 331, 21))
        self.test_coef.setObjectName("test_coef")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 290, 611, 341))
        self.groupBox_3.setObjectName("groupBox_3")
        self.format_convert = QtWidgets.QPushButton(self.groupBox_3)
        self.format_convert.setGeometry(QtCore.QRect(170, 200, 121, 51))
        self.format_convert.setObjectName("format_convert")
        self.config_generate = QtWidgets.QPushButton(self.groupBox_3)
        self.config_generate.setGeometry(QtCore.QRect(310, 200, 121, 51))
        self.config_generate.setObjectName("config_generate")
        self.train_yolo = QtWidgets.QPushButton(self.groupBox_3)
        self.train_yolo.setGeometry(QtCore.QRect(450, 200, 121, 51))
        self.train_yolo.setObjectName("train_yolo")
        self.train_allstep = QtWidgets.QPushButton(self.groupBox_3)
        self.train_allstep.setGeometry(QtCore.QRect(30, 270, 121, 51))
        self.train_allstep.setObjectName("train_allstep")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(30, 23, 72, 15))
        self.label_6.setObjectName("label_6")
        self.test_oneimage = QtWidgets.QPushButton(self.groupBox_3)
        self.test_oneimage.setGeometry(QtCore.QRect(170, 270, 121, 51))
        self.test_oneimage.setObjectName("test_oneimage")
        self.compute_mAP = QtWidgets.QPushButton(self.groupBox_3)
        self.compute_mAP.setGeometry(QtCore.QRect(310, 270, 121, 51))
        self.compute_mAP.setObjectName("compute_mAP")
        self.trainsetSetup = QtWidgets.QPushButton(self.groupBox_3)
        self.trainsetSetup.setGeometry(QtCore.QRect(30, 200, 121, 51))
        self.trainsetSetup.setObjectName("trainsetSetup")
        self.stopTrain = QtWidgets.QPushButton(self.groupBox_3)
        self.stopTrain.setGeometry(QtCore.QRect(450, 270, 121, 51))
        self.stopTrain.setObjectName("stopTrain")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(30, 89, 72, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(30, 121, 101, 16))
        self.label_8.setObjectName("label_8")
        self.test_type = QtWidgets.QComboBox(self.groupBox_3)
        self.test_type.setGeometry(QtCore.QRect(170, 85, 331, 22))
        self.test_type.setObjectName("test_type")
        self.test_type.addItem("")
        self.test_type.addItem("")
        self.test_type.addItem("")
        self.image_postfix = QtWidgets.QComboBox(self.groupBox_3)
        self.image_postfix.setGeometry(QtCore.QRect(170, 120, 331, 22))
        self.image_postfix.setObjectName("image_postfix")
        self.image_postfix.addItem("")
        self.image_postfix.addItem("")
        self.image_postfix.addItem("")
        self.image_postfix.addItem("")
        self.image_postfix.addItem("")
        self.image_postfix.addItem("")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(30, 57, 72, 15))
        self.label_9.setObjectName("label_9")
        self.test_thresh = QtWidgets.QLineEdit(self.groupBox_3)
        self.test_thresh.setGeometry(QtCore.QRect(170, 52, 331, 21))
        self.test_thresh.setObjectName("test_thresh")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(30, 160, 72, 15))
        self.label_10.setObjectName("label_10")
        self.modelType = QtWidgets.QComboBox(self.groupBox_3)
        self.modelType.setGeometry(QtCore.QRect(170, 160, 331, 22))
        self.modelType.setObjectName("modelType")
        self.modelType.addItem("")
        self.modelType.addItem("")
        self.modelType.addItem("")
        self.batchsize = QtWidgets.QSpinBox(self.groupBox_3)
        self.batchsize.setGeometry(QtCore.QRect(170, 20, 331, 22))
        self.batchsize.setProperty("value", 4)
        self.batchsize.setObjectName("batchsize")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YOLOV3可视化训练系统"))
        self.groupBox.setTitle(_translate("MainWindow", "设置路径"))
        self.label.setText(_translate("MainWindow", "VOC2007格式路径"))
        self.label_2.setText(_translate("MainWindow", "YOLOV3配置路径"))
        self.yolo_path.setText(_translate("MainWindow", "./yolov3_train"))
        self.vocSetup.setText(_translate("MainWindow", "选择"))
        self.yoloSetup.setText(_translate("MainWindow", "选择"))
        self.groupBox_2.setTitle(_translate("MainWindow", "训练、验证和测试样本比例"))
        self.label_3.setText(_translate("MainWindow", "训练样本比例"))
        self.label_4.setText(_translate("MainWindow", "验证样本比例"))
        self.label_5.setText(_translate("MainWindow", "测试样本比例"))
        self.train_coef.setText(_translate("MainWindow", "0.9"))
        self.val_coef.setText(_translate("MainWindow", "0.05"))
        self.test_coef.setText(_translate("MainWindow", "0.05"))
        self.groupBox_3.setTitle(_translate("MainWindow", "训练参数及训练步骤"))
        self.format_convert.setText(_translate("MainWindow", "VOC格式转换"))
        self.config_generate.setText(_translate("MainWindow", "配置文件生成"))
        self.train_yolo.setText(_translate("MainWindow", "训练YOLOV3"))
        self.train_allstep.setText(_translate("MainWindow", "一键训练"))
        self.label_6.setText(_translate("MainWindow", "批大小"))
        self.test_oneimage.setText(_translate("MainWindow", "测试单幅图像"))
        self.compute_mAP.setText(_translate("MainWindow", "计算mAP"))
        self.trainsetSetup.setText(_translate("MainWindow", "切分数据集"))
        self.stopTrain.setText(_translate("MainWindow", "结束训练"))
        self.label_7.setText(_translate("MainWindow", "测试集"))
        self.label_8.setText(_translate("MainWindow", "图像文件后缀"))
        self.test_type.setItemText(0, _translate("MainWindow", "train"))
        self.test_type.setItemText(1, _translate("MainWindow", "val"))
        self.test_type.setItemText(2, _translate("MainWindow", "test"))
        self.image_postfix.setItemText(0, _translate("MainWindow", ".jpg"))
        self.image_postfix.setItemText(1, _translate("MainWindow", ".jpeg"))
        self.image_postfix.setItemText(2, _translate("MainWindow", ".bmp"))
        self.image_postfix.setItemText(3, _translate("MainWindow", ".png"))
        self.image_postfix.setItemText(4, _translate("MainWindow", ".tif"))
        self.image_postfix.setItemText(5, _translate("MainWindow", ".tiff"))
        self.label_9.setText(_translate("MainWindow", "测试阈值"))
        self.test_thresh.setText(_translate("MainWindow", "0.25"))
        self.label_10.setText(_translate("MainWindow", "YOLO模型"))
        self.modelType.setItemText(0, _translate("MainWindow", "3层模型"))
        self.modelType.setItemText(1, _translate("MainWindow", "4层模型"))
        self.modelType.setItemText(2, _translate("MainWindow", "5层模型"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action.setText(_translate("MainWindow", "退出"))

